# generated by datamodel-codegen:
#   filename:  tmp.4gmNFBUEO9
#   timestamp: 2026-02-02T13:09:10+00:00

from typing import Any, Literal, NotRequired, TypedDict


class SimpleUser(TypedDict):
    """
    A GitHub user.
    """

    name: NotRequired[str]
    email: NotRequired[str]
    login: str
    id: int
    node_id: str
    avatar_url: str
    gravatar_id: str
    url: str
    html_url: str
    followers_url: str
    following_url: str
    gists_url: str
    starred_url: str
    subscriptions_url: str
    organizations_url: str
    repos_url: str
    events_url: str
    received_events_url: str
    type: str
    site_admin: bool
    starred_at: NotRequired[str]
    user_view_type: NotRequired[str]


class Permissions(TypedDict, extra_items=str):
    """
    The set of permissions for the GitHub app
    """

    issues: NotRequired[str]
    checks: NotRequired[str]
    metadata: NotRequired[str]
    contents: NotRequired[str]
    deployments: NotRequired[str]


class AppPermissions(TypedDict):
    """
    The permissions granted to the user access token.
    """

    actions: NotRequired[Literal["read", "write"]]
    administration: NotRequired[Literal["read", "write"]]
    artifact_metadata: NotRequired[Literal["read", "write"]]
    attestations: NotRequired[Literal["read", "write"]]
    checks: NotRequired[Literal["read", "write"]]
    codespaces: NotRequired[Literal["read", "write"]]
    contents: NotRequired[Literal["read", "write"]]
    dependabot_secrets: NotRequired[Literal["read", "write"]]
    deployments: NotRequired[Literal["read", "write"]]
    discussions: NotRequired[Literal["read", "write"]]
    environments: NotRequired[Literal["read", "write"]]
    issues: NotRequired[Literal["read", "write"]]
    merge_queues: NotRequired[Literal["read", "write"]]
    metadata: NotRequired[Literal["read", "write"]]
    packages: NotRequired[Literal["read", "write"]]
    pages: NotRequired[Literal["read", "write"]]
    pull_requests: NotRequired[Literal["read", "write"]]
    repository_custom_properties: NotRequired[Literal["read", "write"]]
    repository_hooks: NotRequired[Literal["read", "write"]]
    repository_projects: NotRequired[Literal["read", "write", "admin"]]
    secret_scanning_alerts: NotRequired[Literal["read", "write"]]
    secrets: NotRequired[Literal["read", "write"]]
    security_events: NotRequired[Literal["read", "write"]]
    single_file: NotRequired[Literal["read", "write"]]
    statuses: NotRequired[Literal["read", "write"]]
    vulnerability_alerts: NotRequired[Literal["read", "write"]]
    workflows: NotRequired[Literal["write"]]
    custom_properties_for_organizations: NotRequired[Literal["read", "write"]]
    members: NotRequired[Literal["read", "write"]]
    organization_administration: NotRequired[Literal["read", "write"]]
    organization_custom_roles: NotRequired[Literal["read", "write"]]
    organization_custom_org_roles: NotRequired[Literal["read", "write"]]
    organization_custom_properties: NotRequired[Literal["read", "write", "admin"]]
    organization_copilot_seat_management: NotRequired[Literal["write"]]
    organization_announcement_banners: NotRequired[Literal["read", "write"]]
    organization_events: NotRequired[Literal["read"]]
    organization_hooks: NotRequired[Literal["read", "write"]]
    organization_personal_access_tokens: NotRequired[Literal["read", "write"]]
    organization_personal_access_token_requests: NotRequired[Literal["read", "write"]]
    organization_plan: NotRequired[Literal["read"]]
    organization_projects: NotRequired[Literal["read", "write", "admin"]]
    organization_packages: NotRequired[Literal["read", "write"]]
    organization_secrets: NotRequired[Literal["read", "write"]]
    organization_self_hosted_runners: NotRequired[Literal["read", "write"]]
    organization_user_blocking: NotRequired[Literal["read", "write"]]
    team_discussions: NotRequired[Literal["read", "write"]]
    email_addresses: NotRequired[Literal["read", "write"]]
    followers: NotRequired[Literal["read", "write"]]
    git_ssh_keys: NotRequired[Literal["read", "write"]]
    gpg_keys: NotRequired[Literal["read", "write"]]
    interaction_limits: NotRequired[Literal["read", "write"]]
    profile: NotRequired[Literal["write"]]
    starring: NotRequired[Literal["read", "write"]]
    enterprise_custom_properties_for_organizations: NotRequired[Literal["read", "write", "admin"]]


class NullableSimpleUser(TypedDict):
    """
    A GitHub user.
    """

    name: NotRequired[str]
    email: NotRequired[str]
    login: str
    id: int
    node_id: str
    avatar_url: str
    gravatar_id: str
    url: str
    html_url: str
    followers_url: str
    following_url: str
    gists_url: str
    starred_url: str
    subscriptions_url: str
    organizations_url: str
    repos_url: str
    events_url: str
    received_events_url: str
    type: str
    site_admin: bool
    starred_at: NotRequired[str]
    user_view_type: NotRequired[str]


class NullableLicenseSimple(TypedDict):
    """
    License Simple
    """

    key: str
    name: str
    url: str
    spdx_id: str
    node_id: str
    html_url: NotRequired[str]


class Permissions1(TypedDict):
    admin: bool
    pull: bool
    triage: NotRequired[bool]
    push: bool
    maintain: NotRequired[bool]


class CodeSearchIndexStatus(TypedDict):
    """
    The status of the code search index for this repository
    """

    lexical_search_ok: NotRequired[bool]
    lexical_commit_sha: NotRequired[str]


class Repository(TypedDict):
    """
    A repository on GitHub.
    """

    id: int
    node_id: str
    name: str
    full_name: str
    license: NullableLicenseSimple
    forks: int
    permissions: NotRequired[Permissions1]
    owner: SimpleUser
    private: bool
    html_url: str
    description: str
    fork: bool
    url: str
    archive_url: str
    assignees_url: str
    blobs_url: str
    branches_url: str
    collaborators_url: str
    comments_url: str
    commits_url: str
    compare_url: str
    contents_url: str
    contributors_url: str
    deployments_url: str
    downloads_url: str
    events_url: str
    forks_url: str
    git_commits_url: str
    git_refs_url: str
    git_tags_url: str
    git_url: str
    issue_comment_url: str
    issue_events_url: str
    issues_url: str
    keys_url: str
    labels_url: str
    languages_url: str
    merges_url: str
    milestones_url: str
    notifications_url: str
    pulls_url: str
    releases_url: str
    ssh_url: str
    stargazers_url: str
    statuses_url: str
    subscribers_url: str
    subscription_url: str
    tags_url: str
    teams_url: str
    trees_url: str
    clone_url: str
    mirror_url: str
    hooks_url: str
    svn_url: str
    homepage: str
    language: str
    forks_count: int
    stargazers_count: int
    watchers_count: int
    size: int
    default_branch: str
    open_issues_count: int
    is_template: NotRequired[bool]
    topics: NotRequired[list[str]]
    has_issues: bool
    has_projects: bool
    has_wiki: bool
    has_pages: bool
    has_downloads: bool
    has_discussions: NotRequired[bool]
    archived: bool
    disabled: bool
    visibility: NotRequired[str]
    pushed_at: str
    created_at: str
    updated_at: str
    allow_rebase_merge: NotRequired[bool]
    temp_clone_token: NotRequired[str]
    allow_squash_merge: NotRequired[bool]
    allow_auto_merge: NotRequired[bool]
    delete_branch_on_merge: NotRequired[bool]
    allow_update_branch: NotRequired[bool]
    use_squash_pr_title_as_default: NotRequired[bool]
    squash_merge_commit_title: NotRequired[Literal["PR_TITLE", "COMMIT_OR_PR_TITLE"]]
    squash_merge_commit_message: NotRequired[Literal["PR_BODY", "COMMIT_MESSAGES", "BLANK"]]
    merge_commit_title: NotRequired[Literal["PR_TITLE", "MERGE_MESSAGE"]]
    merge_commit_message: NotRequired[Literal["PR_BODY", "PR_TITLE", "BLANK"]]
    allow_merge_commit: NotRequired[bool]
    allow_forking: NotRequired[bool]
    web_commit_signoff_required: NotRequired[bool]
    open_issues: int
    watchers: int
    master_branch: NotRequired[str]
    starred_at: NotRequired[str]
    anonymous_access_enabled: NotRequired[bool]
    code_search_index_status: NotRequired[CodeSearchIndexStatus]


class SimpleRepository(TypedDict):
    """
    A GitHub repository.
    """

    id: int
    node_id: str
    name: str
    full_name: str
    owner: SimpleUser
    private: bool
    html_url: str
    description: str
    fork: bool
    url: str
    archive_url: str
    assignees_url: str
    blobs_url: str
    branches_url: str
    collaborators_url: str
    comments_url: str
    commits_url: str
    compare_url: str
    contents_url: str
    contributors_url: str
    deployments_url: str
    downloads_url: str
    events_url: str
    forks_url: str
    git_commits_url: str
    git_refs_url: str
    git_tags_url: str
    issue_comment_url: str
    issue_events_url: str
    issues_url: str
    keys_url: str
    labels_url: str
    languages_url: str
    merges_url: str
    milestones_url: str
    notifications_url: str
    pulls_url: str
    releases_url: str
    stargazers_url: str
    statuses_url: str
    subscribers_url: str
    subscription_url: str
    tags_url: str
    teams_url: str
    trees_url: str
    hooks_url: str


class Label(TypedDict):
    """
    Color-coded labels help you categorize and filter your issues (just like labels in Gmail).
    """

    id: int
    node_id: str
    url: str
    name: str
    description: str
    color: str
    default: bool


class NullableMilestone(TypedDict):
    """
    A collection of related issues and pull requests.
    """

    url: str
    html_url: str
    labels_url: str
    id: int
    node_id: str
    number: int
    state: Literal["open", "closed"]
    title: str
    description: str
    creator: NullableSimpleUser
    open_issues: int
    closed_issues: int
    created_at: str
    updated_at: str
    closed_at: str
    due_on: str


class Permissions2(TypedDict, extra_items=str):
    """
    The set of permissions for the GitHub app
    """

    issues: NotRequired[str]
    checks: NotRequired[str]
    metadata: NotRequired[str]
    contents: NotRequired[str]
    deployments: NotRequired[str]


ReactionRollup = TypedDict(
    "ReactionRollup",
    {
        "url": str,
        "total_count": int,
        "+1": int,
        "-1": int,
        "laugh": int,
        "confused": int,
        "heart": int,
        "hooray": int,
        "eyes": int,
        "rocket": int,
    },
)


class LicenseSimple(TypedDict):
    """
    License Simple
    """

    key: str
    name: str
    url: str
    spdx_id: str
    node_id: str
    html_url: NotRequired[str]


class AdvancedSecurity(TypedDict):
    """
    Enable or disable GitHub Advanced Security for the repository.

    For standalone Code Scanning or Secret Protection products, this parameter cannot be used.

    """

    status: NotRequired[Literal["enabled", "disabled"]]


class CodeSecurity(TypedDict):
    status: NotRequired[Literal["enabled", "disabled"]]


class DependabotSecurityUpdates(TypedDict):
    """
    Enable or disable Dependabot security updates for the repository.
    """

    status: NotRequired[Literal["enabled", "disabled"]]


class SecretScanning(TypedDict):
    status: NotRequired[Literal["enabled", "disabled"]]


class SecretScanningPushProtection(TypedDict):
    status: NotRequired[Literal["enabled", "disabled"]]


class SecretScanningNonProviderPatterns(TypedDict):
    status: NotRequired[Literal["enabled", "disabled"]]


class SecretScanningAiDetection(TypedDict):
    status: NotRequired[Literal["enabled", "disabled"]]


class SecurityAndAnalysis(TypedDict):
    advanced_security: NotRequired[AdvancedSecurity]
    code_security: NotRequired[CodeSecurity]
    dependabot_security_updates: NotRequired[DependabotSecurityUpdates]
    secret_scanning: NotRequired[SecretScanning]
    secret_scanning_push_protection: NotRequired[SecretScanningPushProtection]
    secret_scanning_non_provider_patterns: NotRequired[SecretScanningNonProviderPatterns]
    secret_scanning_ai_detection: NotRequired[SecretScanningAiDetection]


class Permissions3(TypedDict):
    admin: NotRequired[bool]
    maintain: NotRequired[bool]
    push: NotRequired[bool]
    triage: NotRequired[bool]
    pull: NotRequired[bool]


class License(TypedDict):
    key: NotRequired[str]
    name: NotRequired[str]
    spdx_id: NotRequired[str]
    url: NotRequired[str]
    node_id: NotRequired[str]


class Permissions4(TypedDict):
    admin: bool
    pull: bool
    triage: NotRequired[bool]
    push: bool
    maintain: NotRequired[bool]


class NullableRepository(TypedDict):
    """
    A repository on GitHub.
    """

    id: int
    node_id: str
    name: str
    full_name: str
    license: NullableLicenseSimple
    forks: int
    permissions: NotRequired[Permissions4]
    owner: SimpleUser
    private: bool
    html_url: str
    description: str
    fork: bool
    url: str
    archive_url: str
    assignees_url: str
    blobs_url: str
    branches_url: str
    collaborators_url: str
    comments_url: str
    commits_url: str
    compare_url: str
    contents_url: str
    contributors_url: str
    deployments_url: str
    downloads_url: str
    events_url: str
    forks_url: str
    git_commits_url: str
    git_refs_url: str
    git_tags_url: str
    git_url: str
    issue_comment_url: str
    issue_events_url: str
    issues_url: str
    keys_url: str
    labels_url: str
    languages_url: str
    merges_url: str
    milestones_url: str
    notifications_url: str
    pulls_url: str
    releases_url: str
    ssh_url: str
    stargazers_url: str
    statuses_url: str
    subscribers_url: str
    subscription_url: str
    tags_url: str
    teams_url: str
    trees_url: str
    clone_url: str
    mirror_url: str
    hooks_url: str
    svn_url: str
    homepage: str
    language: str
    forks_count: int
    stargazers_count: int
    watchers_count: int
    size: int
    default_branch: str
    open_issues_count: int
    is_template: NotRequired[bool]
    topics: NotRequired[list[str]]
    has_issues: bool
    has_projects: bool
    has_wiki: bool
    has_pages: bool
    has_downloads: bool
    has_discussions: NotRequired[bool]
    archived: bool
    disabled: bool
    visibility: NotRequired[str]
    pushed_at: str
    created_at: str
    updated_at: str
    allow_rebase_merge: NotRequired[bool]
    temp_clone_token: NotRequired[str]
    allow_squash_merge: NotRequired[bool]
    allow_auto_merge: NotRequired[bool]
    delete_branch_on_merge: NotRequired[bool]
    allow_update_branch: NotRequired[bool]
    use_squash_pr_title_as_default: NotRequired[bool]
    squash_merge_commit_title: NotRequired[Literal["PR_TITLE", "COMMIT_OR_PR_TITLE"]]
    squash_merge_commit_message: NotRequired[Literal["PR_BODY", "COMMIT_MESSAGES", "BLANK"]]
    merge_commit_title: NotRequired[Literal["PR_TITLE", "MERGE_MESSAGE"]]
    merge_commit_message: NotRequired[Literal["PR_BODY", "PR_TITLE", "BLANK"]]
    allow_merge_commit: NotRequired[bool]
    allow_forking: NotRequired[bool]
    web_commit_signoff_required: NotRequired[bool]
    open_issues: int
    watchers: int
    master_branch: NotRequired[str]
    starred_at: NotRequired[str]
    anonymous_access_enabled: NotRequired[bool]
    code_search_index_status: NotRequired[CodeSearchIndexStatus]


class CodeOfConductSimple(TypedDict):
    """
    Code of Conduct Simple
    """

    url: str
    key: str
    name: str
    html_url: str


class Integration(TypedDict):
    """
    GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub.
    """

    id: int
    slug: NotRequired[str]
    node_id: str
    client_id: NotRequired[str]
    owner: SimpleUser | Any
    name: str
    description: str
    external_url: str
    html_url: str
    created_at: str
    updated_at: str
    permissions: Permissions
    events: list[str]
    installations_count: NotRequired[int]


class NullableIntegration(TypedDict):
    """
    GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub.
    """

    id: int
    slug: NotRequired[str]
    node_id: str
    client_id: NotRequired[str]
    owner: SimpleUser | Any
    name: str
    description: str
    external_url: str
    html_url: str
    created_at: str
    updated_at: str
    permissions: Permissions2
    events: list[str]
    installations_count: NotRequired[int]


class IssueComment(TypedDict):
    """
    Comments provide a way for people to collaborate on an issue.
    """

    id: int
    node_id: str
    url: str
    body: NotRequired[str]
    body_text: NotRequired[str]
    body_html: NotRequired[str]
    html_url: str
    user: NullableSimpleUser
    created_at: str
    updated_at: str
    issue_url: str
    author_association: NotRequired[
        Literal[
            "COLLABORATOR",
            "CONTRIBUTOR",
            "FIRST_TIMER",
            "FIRST_TIME_CONTRIBUTOR",
            "MANNEQUIN",
            "MEMBER",
            "NONE",
            "OWNER",
        ]
    ]
    performed_via_github_app: NotRequired[NullableIntegration]
    reactions: NotRequired[ReactionRollup]


class MinimalRepository(TypedDict):
    """
    Minimal Repository
    """

    id: int
    node_id: str
    name: str
    full_name: str
    owner: SimpleUser
    private: bool
    html_url: str
    description: str
    fork: bool
    url: str
    archive_url: str
    assignees_url: str
    blobs_url: str
    branches_url: str
    collaborators_url: str
    comments_url: str
    commits_url: str
    compare_url: str
    contents_url: str
    contributors_url: str
    deployments_url: str
    downloads_url: str
    events_url: str
    forks_url: str
    git_commits_url: str
    git_refs_url: str
    git_tags_url: str
    git_url: NotRequired[str]
    issue_comment_url: str
    issue_events_url: str
    issues_url: str
    keys_url: str
    labels_url: str
    languages_url: str
    merges_url: str
    milestones_url: str
    notifications_url: str
    pulls_url: str
    releases_url: str
    ssh_url: NotRequired[str]
    stargazers_url: str
    statuses_url: str
    subscribers_url: str
    subscription_url: str
    tags_url: str
    teams_url: str
    trees_url: str
    clone_url: NotRequired[str]
    mirror_url: NotRequired[str]
    hooks_url: str
    svn_url: NotRequired[str]
    homepage: NotRequired[str]
    language: NotRequired[str]
    forks_count: NotRequired[int]
    stargazers_count: NotRequired[int]
    watchers_count: NotRequired[int]
    size: NotRequired[int]
    default_branch: NotRequired[str]
    open_issues_count: NotRequired[int]
    is_template: NotRequired[bool]
    topics: NotRequired[list[str]]
    has_issues: NotRequired[bool]
    has_projects: NotRequired[bool]
    has_wiki: NotRequired[bool]
    has_pages: NotRequired[bool]
    has_downloads: NotRequired[bool]
    has_discussions: NotRequired[bool]
    archived: NotRequired[bool]
    disabled: NotRequired[bool]
    visibility: NotRequired[str]
    pushed_at: NotRequired[str]
    created_at: NotRequired[str]
    updated_at: NotRequired[str]
    permissions: NotRequired[Permissions3]
    role_name: NotRequired[str]
    temp_clone_token: NotRequired[str]
    delete_branch_on_merge: NotRequired[bool]
    subscribers_count: NotRequired[int]
    network_count: NotRequired[int]
    code_of_conduct: NotRequired[Any]
    license: NotRequired[License]
    forks: NotRequired[int]
    open_issues: NotRequired[int]
    watchers: NotRequired[int]
    allow_forking: NotRequired[bool]
    web_commit_signoff_required: NotRequired[bool]
    security_and_analysis: NotRequired[SecurityAndAnalysis]
    custom_properties: NotRequired[dict[str, Any]]


class Deployment(TypedDict):
    """
    A request for a specific ref(branch,sha,tag) to be deployed
    """

    url: str
    id: int
    node_id: str
    sha: str
    ref: str
    task: str
    payload: dict[str, Any] | str
    original_environment: NotRequired[str]
    environment: str
    description: str
    creator: NullableSimpleUser
    created_at: str
    updated_at: str
    statuses_url: str
    repository_url: str
    transient_environment: NotRequired[bool]
    production_environment: NotRequired[bool]
    performed_via_github_app: NotRequired[NullableIntegration]


class DeploymentStatus(TypedDict):
    """
    The status of a deployment.
    """

    url: str
    id: int
    node_id: str
    state: Literal["error", "failure", "inactive", "pending", "success", "queued", "in_progress"]
    creator: NullableSimpleUser
    description: str
    environment: NotRequired[str]
    target_url: str
    created_at: str
    updated_at: str
    deployment_url: str
    repository_url: str
    environment_url: NotRequired[str]
    log_url: NotRequired[str]
    performed_via_github_app: NotRequired[NullableIntegration]
